baseURL = "https://rsk3d.no/"
languageCode = "en-us"
title = "RSK3D"
theme = "PaperMod"
relativeURLs = true
canonifyURLs = true

[params]
  homeInfoParams = { Title = "Hi, I'm RSK3D ðŸ‘‹", Content = "3D Designer â€¢ Developer â€¢ Tech Enthusiast" }
  ShowReadingTime = false
  ShowBreadCrumbs = false
  ShowPostNavLinks = false
  ShowCodeCopyButtons = true
  defaultTheme = "dark"


[[params.socialIcons]]
  name = "github"
  url = "https://github.com/thisprey"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/richard-k-29b92784"

[[params.socialIcons]]
  name = "email"
  url = "mailto:contact@rsk3d.com"