baseURL = "https://rsk3d.no/"
languageCode = "en-us"
title = "RSK3D"
theme = "PaperMod"
relativeURLs = true
canonifyURLs = true

[params]
  homeInfoParams = { Title = "Hi, I'm RSK3D ðŸ‘‹", Content = "3D Designer â€¢ Developer â€¢ Tech Enthusiast" }
  ShowReadingTime = false
  ShowBreadCrumbs = false
  ShowPostNavLinks = false
  ShowCodeCopyButtons = true
  defaultTheme = "dark"
